# Variables taken from config.* files:
config_files:

  # config.base:
  FHMAX_GFS:    !Immediate [ !calc ' int(tools.env("FHMAX_GFS"),10) ' ]
  FHMIN_GFS:    !Immediate [ !calc ' int(tools.env("FHMIN_GFS"),10) ' ]
  FHOUT_GFS:    !Immediate [ !calc ' int(tools.env("FHOUT_GFS"),10) ' ]
  FHMAX:        !Immediate [ !calc ' int(tools.env("FHMAX"),10) ' ]
  FHMIN:        !Immediate [ !calc ' int(tools.env("FHMIN"),10) ' ]
  FHOUT:        !Immediate [ !calc ' int(tools.env("FHOUT"),10) ' ]
  FHMAX_HF_GFS: !Immediate [ !calc ' int(tools.env("FHMAX_HF_GFS"),10) ' ]
  FHOUT_HF_GFS: !Immediate [ !calc ' int(tools.env("FHOUT_HF_GFS"),10) ' ]
  PSLOT:        !Immediate [ !calc tools.env("PSLOT") ]
  EXPDIR:       !Immediate [ !calc tools.env("EXPDIR") ]
  ROTDIR:       !Immediate [ !calc tools.env("ROTDIR") ]
  RUNDIR:       !Immediate [ !calc tools.env("RUNDIR") ]
  HOMEgfs:      !Immediate [ !calc tools.env("HOMEgfs") ]
  CASE:         !Immediate [ !calc tools.env("CASE") ]
  CASE_ENKF:    !Immediate [ !calc tools.env("CASE_ENKF") ]
  SDATE:        !Immediate [ !calc tools.env("SDATE") ]
  EDATE:        !Immediate [ !calc tools.env("EDATE") ]
  NMEM_ENKF:    !Immediate [ !calc ' int( tools.env("NMEM_ENKF"),10 )']
  DMPDIR:       !Immediate [ !calc tools.env("DMPDIR") ]
  QUEUE:        !Immediate [ !calc tools.env("QUEUE") ]
  QUEUE_ARCH:   !Immediate [ !calc tools.env("QUEUE_ARCH") ]
  ACCOUNT:      !Immediate [ !calc tools.env("ACCOUNT") ]
  machine:      !Immediate [ !calc tools.env("machine") ]

  # config.eobs:
  NMEM_EOMGGRP: !Immediate [ !calc ' int(tools.env("NMEM_EOMGGRP"),10) ' ]

  # config.efcs:
  NMEM_EFCSGRP: !Immediate [ !calc ' int(tools.env("NMEM_EFCSGRP"),10) ' ]

  # config.earc:
  NMEM_EARCGRP: !Immediate [ !calc ' int(tools.env("NMEM_EARCGRP"),10) ' ]

  # config.fcst / config.fv3:
  layout_x:     !Immediate [ !calc ' int(tools.env("layout_x"),10) ' ]
  layout_y:     !Immediate [ !calc ' int(tools.env("layout_y"),10) ' ]
  WRITE_GROUP:  !Immediate [ !calc ' int(tools.env("WRITE_GROUP"),10) ' ]
  WRTTASK_PER_GROUP: !Immediate
    - !calc int(tools.env("WRTTASK_PER_GROUP"),10)

  # config.efcs / config.fv3:
  ENKF_layout_x:     !Immediate
    - !calc ' int(tools.env("ENKF_layout_x"),10) '
  ENKF_layout_y:     !Immediate
    - !calc ' int(tools.env("ENKF_layout_y"),10) '
  ENKF_WRITE_GROUP:  !Immediate
    - !calc ' int(tools.env("ENKF_WRITE_GROUP"),10) '
  ENKF_WRTTASK_PER_GROUP: !Immediate
    - !calc int(tools.env("ENKF_WRTTASK_PER_GROUP"),10)
