settings:
  NMEM_ENKF: 80
  ENKF_GROUPS: 16

  ENKF_INNOVATE_GROUPS: !calc ENKF_GROUPS
  ENKF_FORECAST_GROUPS: !calc ENKF_GROUPS
  ENKF_ARCHIVE_GROUPS: !calc ENKF_GROUPS

  ECF_HOME: '/gpfs/hps3/emc/hwrf/noscrub/Bin.Liu/save/gitCROW/model/ecflow_fv3gfs'
  ROCOTO_HOMEgfs: !calc ECF_HOME # Would be different in the real execution
  ROCOTO_HOME: !calc ECF_HOME
  layout_x: 8
  layout_y: 16
  experiment_name: ecfgfsfv3
  QUEUE: debug
  PROJECT: GFS-T2O
  QUEUESERV: dev_transfer

  # NOTE TO SELF: replace experiment_name with %EMCPEN%
  COM: !expand '/gpfs/hps2/ptmp/emc.glopara/{experiment_name}/com'
  DATAROOT: !expand '/gpfs/hps2/stmp/emc.glopara/{experiment_name}'
