
## initial_directory: location from which the setup script was run.
initial_directory: !calc ( tools.realpath(tools.abspath(".")) )

settings:
  HOMEgfs: "/gpfs/hps3/emc/global/noscrub/emc.glopara/CROW/snapshot_master_20180209/gfs.v15.0.0"
  COM: !expand '/gpfs/hps2/ptmp/$USER/{experiment_name}'
  EXPDIR: !expand '/gpfs/hps3/emc/global/noscrub/$USER/para_fv3gfs/{experiment_name}'
  DATAROOT: !expand '/gpfs/hps2/stmp/$USER/{experiment_name}'
  experiment_name: QSLOT

  NMEM_ENKF: 20
  ENKF_GROUPS: 2

  ENKF_INNOVATE_GROUPS: !calc ENKF_GROUPS
  ENKF_FORECAST_GROUPS: !calc ENKF_GROUPS
  ENKF_ARCHIVE_GROUPS: 3

  ECF_HOME: !calc ( doc.initial_directory )
  ROCOTO_HOME: !calc ( doc.initial_directory )
  layout_x: 4
  layout_y: 6
  WRITE_GROUP: 2
  WRTTASK_PER_GROUP: 24
  QUEUE: dev
  PROJECT: FV3GFS-T2O
  QUEUESERV: dev_transfer
  QUEUESHARED: dev_shared

  DUMPDIR: "/gpfs/tp1/emc/globaldump"

  start_date: 2018-01-05t00:00:00
  end_date: 2018-01-05t06:00:00
  start_date_gfs: !calc ( start_date+tools.to_timedelta('6:00:00') )
  end_date_gfs: !calc end_date
  interval_gfs: !timedelta "12:00:00"
  forecast_hours: !calc tools.seq(0,120,1)+tools.seq(123,240,3)+tools.seq(240,384,12)

  max_job_tries: 1
  realtime: False
  archive_to_hpss: True

scheduler_settings: *automatic_scheduler_settings

########################################################################
